buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.0'
    }
}
apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace = 'app.smallthingz.dict'
    compileSdk = 37
    buildToolsVersion = '37.0.0'

    defaultConfig {
        applicationId 'app.smallthingz.dict'
        minSdk = 28
        targetSdk = 37
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.assets.srcDirs += ['../../frontend/web/dist']
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
