#!/usr/bin/env python3
"""Regenerate Unicode 16.0.0 default lowercase data. Python stdlib only.

Usage: python3 generate_unicode_lower.py DATA_DIRECTORY OUTPUT_FILE
Downloads missing inputs from unicode.org and checks every source SHA-256.
Generation is explicit: builds and the application never need the network.
"""

import hashlib
from pathlib import Path
import sys
from urllib.request import urlopen

VERSION = "16.0.0"
SOURCES = {
    "UnicodeData.txt": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
    "SpecialCasing.txt": "8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451",
    "DerivedCoreProperties.txt": "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd",
}


def source(directory, name):
    path = directory / name
    if not path.exists():
        raw = urlopen(f"https://www.unicode.org/Public/{VERSION}/ucd/{name}", timeout=60).read()
    else:
        raw = path.read_bytes()
    actual = hashlib.sha256(raw).hexdigest()
    if actual != SOURCES[name]:
        raise ValueError(f"{name}: SHA-256 mismatch: {actual}")
    if not path.exists():
        path.write_bytes(raw)
    return raw.decode("utf-8").splitlines()


def rows(lines):
    for line in lines:
        content = line.partition("#")[0].strip()
        if content:
            yield [field.strip() for field in content.split(";")]


def merge_ranges(ranges):
    result = []
    for first, last in sorted(ranges):
        if result and first <= result[-1][1] + 1:
            result[-1] = (result[-1][0], max(last, result[-1][1]))
        else:
            result.append((first, last))
    return result


def lower_ranges(mapping):
    pairs = sorted(mapping.items())
    result = []
    i = 0
    while i < len(pairs):
        first, target = pairs[i]
        delta = target - first
        last = first
        step = 1
        i += 1
        if i < len(pairs):
            following, lowered = pairs[i]
            if following - first in (1, 2) and lowered - following == delta:
                step = following - first
                while i < len(pairs):
                    following, lowered = pairs[i]
                    if following != last + step or lowered - following != delta:
                        break
                    last = following
                    i += 1
        result.append((first, last, step, delta))
    return result


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    directory, output = map(Path, sys.argv[1:])
    directory.mkdir(parents=True, exist_ok=True)
    mapping = {}
    for fields in rows(source(directory, "UnicodeData.txt")):
        if fields[13]:
            mapping[int(fields[0], 16)] = int(fields[13], 16)

    expansions = {}
    context = []
    for fields in rows(source(directory, "SpecialCasing.txt")):
        cp = int(fields[0], 16)
        lowered = tuple(int(item, 16) for item in fields[1].split())
        condition = fields[4]
        if not condition:
            if len(lowered) == 1:
                if lowered[0] != cp:
                    mapping[cp] = lowered[0]
                else:
                    mapping.pop(cp, None)
            else:
                mapping.pop(cp, None)
                expansions[cp] = lowered
        elif not any(item in ("tr", "az", "lt") for item in condition.split()):
            context.append((cp, lowered, condition))
    # The runtime implements the only locale-independent conditional rule in 16.0.
    if context != [(0x03A3, (0x03C2,), "Final_Sigma")]:
        raise ValueError(f"Unimplemented context rules: {context}")

    props = {"Cased": [], "Case_Ignorable": []}
    for fields in rows(source(directory, "DerivedCoreProperties.txt")):
        if fields[1] in props:
            bounds = fields[0].split("..")
            props[fields[1]].append((int(bounds[0], 16), int(bounds[-1], 16)))

    compressed = lower_ranges(mapping)
    reconstructed = {
        cp: cp + delta
        for first, last, step, delta in compressed
        for cp in range(first, last + 1, step)
    }
    if reconstructed != mapping:
        raise ValueError("Lowercase range compression changed mappings")
    if any(a[1] >= b[0] for a, b in zip(compressed, compressed[1:])):
        raise ValueError("Lowercase range bounds overlap")

    lines = [
        "// Generated by tools/generate_unicode_lower.py; do not edit.",
        f"// Unicode {VERSION}: UnicodeData.txt, SpecialCasing.txt, DerivedCoreProperties.txt.",
        "// Sources: https://www.unicode.org/Public/16.0.0/ucd/",
        "// Data copyright (c) 2024 Unicode, Inc. Distributed under Unicode-3.0.",
        "// See UNICODE-LICENSE.txt for the full notice.",
        "",
        f'pub const unicode_version = "{VERSION}";',
        "pub const LowerRange = struct { first: u21, last: u21, step: u2, delta: i32 };",
        "pub const Range = struct { first: u21, last: u21 };",
        "pub const Expansion = struct { cp: u21, lower: []const u21 };",
        "",
        "pub const lower_ranges = [_]LowerRange{",
    ]
    for first, last, step, delta in compressed:
        lines.append(f"    .{{ .first = 0x{first:X}, .last = 0x{last:X}, .step = {step}, .delta = {delta} }},")
    lines += ["};", "", "pub const expansions = [_]Expansion{"]
    for cp, lowered in sorted(expansions.items()):
        values = ", ".join(f"0x{value:X}" for value in lowered)
        lines.append(f"    .{{ .cp = 0x{cp:X}, .lower = &.{{ {values} }} }},")
    lines += ["};"]
    for name, ranges in props.items():
        lines += ["", f"pub const {name.lower()} = [_]Range{{"]
        for first, last in merge_ranges(ranges):
            lines.append(f"    .{{ .first = 0x{first:X}, .last = 0x{last:X} }},")
        lines += ["};"]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{output}: {len(mapping)} simple lowercase mappings in {len(compressed)} ranges, {len(expansions)} expansion(s)")


if __name__ == "__main__":
    main()
